Logger Plugin
iopipe/iopipe-go pull request #30
Opened 2018-07-12 04:56 UTC by kolanos

Closes #29

2018-07-26 15:54 UTC, XerTheSquirrel commented on agent.go
> +	a.log.Debug(fmt.Sprintf("%s wrapped with IOpipe decorator", getFuncName(handler)))
I assume there is no way to add to the existing logger in Go to perform logging?

2018-07-26 17:52 UTC, pselle reviewed
- Looks like commits need to be verified (if you have your gpg setup in GitHub, a squash on merge will do this)
- coverage dropped below threshold (I'm good with an 85% threshold personally)
- Needs README docs

2018-07-26 17:52 UTC, pselle commented on reporter_test.go
> +func TestReporter_getCollectorURL(t *testing.T) {
Nice improvements on the tests here

2018-07-26 17:52 UTC, pselle commented on signer.go
> +	return "https://signer.us-east-1.iopipe.com/"
Should this default to east-1 or west-2? (I think we default to west-2 in newer services?)

2018-07-27 13:28 UTC, XerTheSquirrel requested changes
Looks good, although there is Pam's question about the signer URL that is used outside of unsupported regions.

2018-07-27 16:10 UTC, XerTheSquirrel approved these changes

2018-07-27 16:12 UTC, XerTheSquirrel commented
The new changes look good, for the signer default fallback URL for unsupported regions I can create a new issue for that so that way it matches the other two agents.

2018-07-30 18:47 UTC, merged